### ISSUE TITLE
android file read issues

### ISSUE THREAD

**Issue by caver456** [ncssar/sign-in#32]
Scanning for valid rosters and valid csvs - though it does read the roster data OK except for file time:
```
INFO   ] beginning scan for valid roster files in directory /data/data/org.test.signin/files/app
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/app/main.py", line 1111, in <module>
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/app.py", line 829, in run
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/app/main.py", line 158, in build
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/app/main.py", line 376, in scanForRosters
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/codecs.py", line 322, in decode
[WARNING] stderr: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 736: invalid start byte
```

**Comment by caver456** [comment]
read csv also works

**Comment by caver456** [comment]
fixed in same manner as readRoster:
```
            # on android, default encoding (utf-8) resulted in failure to read roster
            #  with the following error after opening but before the first row is read:
            # [WARNING] 'utf-8' codec can't decode byte 0xb4 in position 736: invalid start byte
            #  (0xb4 is a grave accent which appears in one member's name)
            #  changing to latin-1 solved it in this case, but a better catch-all solution
            #  is probably to use default encoding with a better 'errors' argument:
#             with open(self.details.rosterFileName,'r',encoding='latin-1') as rosterFile:
            with open(self.details.rosterFileName,'r',errors='ignore') as rosterFile:
```
