### ISSUE TITLE
multiple crashes in first few minutes at Rood Center

### ISSUE THREAD

**Issue by caver456** [ncssar/sign-in#55]
likely related to the guest network.

First crash happened when someone tried to look up their name, immediately on typing the first letter/s into the search box.  Not sure which tablet that was.  Recover worked fine but there were a few more crashes in the first few minutes.

Need to analyze logs from 11-4-19

**Comment by caver456** [comment]
In several of the early log files - was this the cause of the crashes?  The log files seem to end in the middle:
[INFO   ] asynchronous request sent:<UrlRequest(Thread-10, started daemon 3436181872)>
[INFO   ]   typed=9
[INFO   ] on_sync_error called:
[INFO   ]   request=<UrlRequest(Thread-10, started daemon 3436181872)>
[INFO   ]     request body=None
[INFO   ]     request headers=None
[INFO   ]   result=[Errno 7] No address associated with hostname

also this line is the final line of multiple logs:

[INFO   ] newEvent called: eventName=None


in a later log file, this sequence is interesting - on_sync_success is called once, but apparently only once.  Subsequent 'sync called' lines do not show any 'on_sync_' lines at all, but there is a clear death at the end of that same log which has already been fixed in code:

[INFO   ] sync called
[INFO   ] asynchronous request sent:<UrlRequest(Thread-1, started daemon 3475175792)>
[WARNING] Base: Unknown <android> provider
[INFO   ] Base: Start application main loop
[INFO   ] on_text called:<__main__.ComboEdit object at 0xcf8448b8>:
[INFO   ] on_options called:<__main__.ComboEdit object at 0xcf8448b8>:[]
[INFO   ] options:[]
[INFO   ] on_sync_success called
[INFO   ] []
[INFO   ] Exiting admin mode
[INFO   ] keyDown: text=3
[INFO   ] sync called
[INFO   ] asynchronous request sent:<UrlRequest(Thread-2, started daemon 3465804144)>
...
...
[INFO   ] keyDown: text=Sign In Now
[INFO   ]   other key pressed.  id=35
[INFO   ] lookup: id=35  name=Grundy, Tom
[INFO   ] roster certs for 35:['IC', 'DR', 'TL', 'E', 'LD']  (raw=IC, DR, TL, E, LD)
[INFO   ] Certifications for 35:[['IC', 'DR', 'TL', 'E', 'LD'], []]
[INFO   ] 35 Grundy, Tom signed in
[INFO   ] calling timeStr:1572919017.14
[INFO   ] sendAction called
[INFO   ] dict:{'ID': '35', 'Name': 'Grundy, Tom', 'Agency': 'NCSSAR', 'Resource': 'IC,DR,TL,E,LD', 'TimeIn': '17:56', 'TimeOut': '--', 'Total': '--', 'InEpoch': 1572919017.14, 'OutEpoch': 0, 'TotalSec': 0, 'CellNum': '123-456-7890', 'Status': 'SignedIn'}
[INFO   ] json:{"ID": "35", "Name": "Grundy, Tom", "Agency": "NCSSAR", "Resource": "IC,DR,TL,E,LD", "TimeIn": "17:56", "TimeOut": "--", "Total": "--", "InEpoch": 1572919017.14, "OutEpoch": 0, "TotalSec": 0, "CellNum": "123-456-7890", "Status": "SignedIn"}
[INFO   ] asynchronous request sent:<UrlRequest(Thread-3, started daemon 3457153392)>
[INFO   ] calling timeStr:1572919017.14
[INFO   ] updated CSV filename:sign-in_Mon_Nov_4_2019_1756.csv
[INFO   ] writeCSV called
[INFO   ] csv file /data/data/org.test.signin/files/app/sign-in_Mon_Nov_4_2019_1756.csv opened
[INFO   ] [['35', 'Grundy, Tom', 'NCSSAR', 'IC,DR,TL,E,LD', '17:56', '--', '--', 1572919017.14, 0, 0, '123-456-7890', 'SignedIn']]
[INFO   ] on_sendAction_failure called:
[INFO   ]   request=<UrlRequest(Thread-3, started daemon 3457153392)>
[INFO   ]     request body={"ID": "35", "Name": "Grundy, Tom", "Agency": "NCSSAR", "Resource": "IC,DR,TL,E,LD", "TimeIn": "17:56", "TimeOut": "--", "Total": "--", "InEpoch": 1572919017.14, "OutEpoch": 0, "TotalSec": 0, "CellNum": "123-456-7890", "Status": "SignedIn"}
[INFO   ]     request headers={'Content-type': 'application/json', 'Accept': 'text/plain'}
[INFO   ]   result=<html><head><title>Document Error: Page not found</title></head>
		<body><h2>Access Error: Page not found</h2>
		<p>Bad request type</p></body></html>
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/app/main.py", line 1637, in <module>
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/app.py", line 855, in run
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/base.py", line 504, in runTouchApp
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/core/window/window_sdl2.py", line 746, in mainloop
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/core/window/window_sdl2.py", line 478, in _mainloop
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/base.py", line 339, in idle
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/clock.py", line 591, in tick
[WARNING] stderr:   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/network/urlrequest.py", line 516, in _dispatch_result
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/app/main.py", line 1130, in on_sendAction_failure
[WARNING] stderr: AttributeError: 'signinApp' object has no attribute 'syncCloudNoneFileName'



*******************
here's another where the need-to-log-in-to-wifi response seems to screw things up - this happens for three log files in a row so is probably the culprit:

[INFO   ] asynchronous request sent:<UrlRequest(Thread-23, started daemon 3288856944)>
[INFO   ]   typed=r
[INFO   ] on_text called:<__main__.ComboEdit object at 0xc61c48b8>:r
[INFO   ] on_options called:<__main__.ComboEdit object at 0xc61c48b8>:['Ramey, David : 58', 'Ramey, Josh : 61', 'Ramsay, Connor : 33', 'Ramspott, Bax : 57', 'Rathjen, Sophie : 76', 'Reese, Nancy', 'Russell, Steven : 90', 'Russo, Mike : 86']
[INFO   ] creating button for Ramey, David : 58
[INFO   ] creating button for Ramey, Josh : 61
[INFO   ] creating button for Ramsay, Connor : 33
[INFO   ] creating button for Ramspott, Bax : 57
[INFO   ] creating button for Rathjen, Sophie : 76
[INFO   ] creating button for Reese, Nancy
[INFO   ] creating button for Russell, Steven : 90
[INFO   ] creating button for Russo, Mike : 86
[INFO   ] options:['Ramey, David : 58', 'Ramey, Josh : 61', 'Ramsay, Connor : 33', 'Ramspott, Bax : 57', 'Rathjen, Sophie : 76', 'Reese, Nancy', 'Russell, Steven : 90', 'Russo, Mike : 86']
[INFO   ] on_sync_success called
[INFO   ] 



<html>



<head>

<base href="http://wifi.nevcounty.net/libsplash.html" />



<title>Nevada County Guest WiFi Splash Page</title>

</head>

<body bgcolor="#FFFFFF">

    <table align="center">

        <tr>

            <td align="center">

                <table border="0" width="800" style="background-image:url(wifisplashheader.jpg);" cellspacing="0" cellpadding="4">

                    <tr>

                        <td align="left">

                            <img src="./logo.gif" width="160" height="160" hspace="40" align="left" />

                        </td>

                        <td>

                            <font color="#ffffff">

                                <center><H1>Nevada County Guest WiFi Wireless Access Usage Agreement</center></H1>

                        </td>

                        <td>

                            &nbsp;&nbsp;

                        </td>

                    </tr>

                </table>

                <form action="http://wifi.nevcounty.net/accept.html">

                    <table height="60%" cellspacing="0" cellpadding="0">

                        <tr>

                            <td align="center" valign="middle">

                                <table width="800" align="center" cellspacing="0" cellpadding="3" bgcolor="#cccccc">

                                    <tr>

                                        <td align="center" valign="middle" colspan="2">

                                            <table width="100%" cellspacing="0" cellpadding="4">

                                                <tr>

                                                    <td>

                                                        

                                                    </td>

                                                    <td>&nbsp;</td>

                                                </tr>

                                                <tr>

                                                    <td>

                                                        <Strong>

                                                            <p>By pressing the "I ACCEPT" button below you are certifying  that you will abide by this <strong>Nevada County Public Internet Wireless Access  Usage Agreement:</strong></p>

                                                            <ol>

                                                                <li>  You acknowledge that using this service is a privilege, not a right, and unauthorized use may result in cancellation of this privilege or, in some cases, criminal prosection. </li>

                                                                <br />

                                                                <li>  You acknowledge that Nevada County has the right, to the extent permitted by law, to monitor or record any and all data and connection activities for the purpose of quality control, usage analysis, legal investigations, or any other legal purpose.</li>

                                                                <br />

                                                                <li>  You acknowledge that if any Nevada County staff becomes aware of activities violating this agreement they may, at their discretion, immediately end any and all Internet sessions, without prior notice, or initiate an investigation with appropriate authorities.  </li>

                                                                <br />

                                                                <li>

                                                                    You also agree to the following:<br />

                                                                    <p>

                                                                        a)&nbsp;Not to use the County's Internet for any purpose that violates federal, state or local laws, to transmit<br />

                                                                        &nbsp; &nbsp; &nbsp;threatening, obscene, or harassing materials, or to cause disruption to others in any way.

                                                                    </p>

                                                                    <p>

                                                                        b)&nbsp; Not to download; or upload materials that infringe copyright laws of the United States or other<br />

                                                                        &nbsp;&nbsp;&nbsp;&nbsp; countries.

                                                                    </p>

                                                                    <p>

                                                                        c)&nbsp; To respect the rights, privacy and sensitivities of others; and refrain from reading the screens of<br />

                                                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;others, attempting to attack or hack other systems, or attempt to intercept, collect or store data<br />&nbsp; &nbsp;&nbsp;&nbsp;about third parties without their knowledge or consent. <br />

                                                                    <p>

                                                                        d)&nbsp; Not to use this service in any manner that may interfere, damage or disrupt Nevada County's or<br />

                                                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;other's property, computing system, network, software or data.

                                                                    </p>

                                                                    <p>

                                                                        e)&nbsp; Not to send unsolicited messages, including without limitation, promotions or advertisements for<br />

                                                                        &nbsp;&nbsp;&nbsp;&nbsp;products or services, "pyramid schemes," "spam," "chain mail" or "junk mail."

                                                                    </p>

                                                                    <p>

                                                                        f)&nbsp; Not to introduce computer viruses or destructive programs into this or any other computing system(s)<br />

                                                                        &nbsp;&nbsp; &nbsp;California Penal code; Sec.502 et. seq.).

                                                                    </p>

                                                                </li>

                                                                <li>  You acknowledge that printing is not available through this service, except as  separately advertised.</li>

                                                                <br />

                                                                <li>  You acknowledge Nevada County staff is not available to provide training on the use of the equipment or for troubleshooting connectivity issues, and neither Nevada County nor it's staff is responsible for monitoring or controlling Internet use by children or adults.  Nevada county is not responsible for protecting Internet users from inaccurate or offensive material or from viruses, malware, other users, etc.  This is an un-filtered Internet connection.  Use at your own risk.</li>

                                                                <br />

                                                                <li>  You acknowledge that Nevada County has no obligation to ensure that this system will work with your system.  Service is only available at designated locations; actual service coverage, speeds and quality may vary.  Service is subject to unavailability, including emergencies, third party service failures, transmission, equipment or network problems or limitations, interference, lack of signal strength, and maintenance and repair, and may be interrupted, refused, limited or curtailed at any time.</li>

                                                                <br />

                                                                <li>  Limitation of Liability: Nevada County shall not be liable, and you hereby waive any and all liabilities, claims, or damages against Nevada County; arising from use of the service including without limitation, punitive, exemplary, incidental, special or consequential damages, loss of privacy or security damages; personal injury or property damages; or any damages whatsoever resulting from interruption or failure of service; lost profits, loss of business, loss of data, loss due to unauthorized access or due to viruses or other harmful components, cost of replacement products and services, the inability to use the service, the content of any data transmission, communication or messagetransmitted to or received by your unit, access to the world wide web, the interception or loss of any data or transmission, or losses resulting from any goods or services purchased, or messages or data received, or transaction entered into through the service.  If you are dissatisfied with the service, or with this Agreement, you understand and acknowledge that your sole and exclusive remedy is to discontinue using the service.  By using the service you acknowledge that your use of the service is at your sole risk.</li></p>

                                                                <p>

                                                                    Press the <strong>"I ACCEPT"</strong> button below to certify that you have read, understand, and will abide by this Agreement.  Doing so will allow you access to the Internet through the Nevada County Public Internet Wireless System.

                                                                    <span style="text-align: left"></span>

                                                                    <span style="text-align: center"></span>

                                                                </p>

                                                    </td>

                                                </tr>

                                                <tr>

                                                    <td>

                                                        

                                                        

                                                    </td>

                                                <tr></tr>

                                    </tr>

                                </table>

                            </td>

                        </tr>

                    </table>

                    <br>

                    <CENTER><input type="submit" value="I ACCEPT"></CENTER>



                </form>

                </td>

            </tr>

        </table>

</body>

</html>
[INFO   ]   entry dict:<
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/app/main.py", line 1637, in <module>
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/app.py", line 855, in run
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/base.py", line 504, in runTouchApp
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/core/window/window_sdl2.py", line 746, in mainloop
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/core/window/window_sdl2.py", line 478, in _mainloop
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/base.py", line 339, in idle
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/clock.py", line 591, in tick
[WARNING] stderr:   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
[WARNING] stderr:   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/platform/build/build/python-installs/signin/kivy/network/urlrequest.py", line 493, in _dispatch_result
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/app/main.py", line 1159, in on_sync_success
[WARNING] stderr:   File "/mnt/c/Users/caver/Documents/GitHub/sign-in/.buildozer/android/app/main.py", line 1159, in <listcomp>
[WARNING] stderr: TypeError: string indices must be integers

**Comment by caver456** [comment]
'string indices must be integers' error is in Tablet1/kivy_19-11-04_5.txt (and _6 and _7).  Notice the last line printed (entry dict:<) is inside on_sync_success; the line numbers are stale by now

**Comment by caver456** [comment]
probably fixed by adding a check to make sure result is an iterable; need to test on local server by purposely returning html or any non-iterable.  Note this same thing could happen on any successful request: type checking should be done on each handler.

**Comment by caver456** [comment]
the crashing is no longer happening, but, see related #56
